### ISSUE TITLE
Seminar 10: JAVA ERROR

### ISSUE THREAD

**Issue by TiamHeydari** [STAT540-UBC/Discussion#259]
@STAT540-UBC/ta_2018 
Dear TAs.
Hi, when i wnat to run this part of code on my macOSX(I have updated my Java):
`enrichmentResult <- precRecall(scores = ermineInputGeneScores, 
                               scoreColumn = 1, # column 1 is the scores 
                               bigIsBetter = TRUE, # larger logFC should be ranked higher
                               annotation = "Generic_human", # ask ermineJ to use the Generic_human annotation file (will automatically download)
                               aspects = "B", # look at only biological processes 
                               iterations = 10000, # 10K sampling iterations so that results are stable
                               geneSetDescription = "GO.xml") # use the GO XML file in current directory`

I get this error, I cant debug it.
`Error in (function (annotation = NULL, aspects = c("Molecular Function", : Something went wrong. Blame the dev Exception in thread "main" java.lang.UnsupportedClassVersionError: ubic/erminej/ErmineJCli : Unsupported major.minor version 52.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) at java.lang.ClassLoader.defineClass(ClassLoader.java:621) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) at java.net.URLClassLoader.access$000(URLClassLoader.java:58) at java.net.URLClassLoader$1.run(URLClassLoader.java:197) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:190) at java.lang.ClassLoader.loadClass(ClassLoader.java:306) at java.lang.ClassLoader.loadClass(ClassLoader.java:295) at java.lang.ClassLoader.loadClass(ClassLoader.java:247) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:`

Thank you very much.

**Comment by TiamHeydari** [comment]
Hi, I used:
`devtools::install_github('PavlidisLab/ermineR')`
then
`ermineR:::findJava()`
the result:
`"/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"`
but I recieve the error.

**Comment by oganm** [comment]
ok. then you can either delete your own java and potentially re-install rJava to make it work or set your own JAVA_HOME by doing  

```
Sys.setenv(JAVA_HOME = 'PATH TO NEW JAVA HOME')
```
before calling ermineR

**Comment by TiamHeydari** [comment]
Thanks a lot! It works!

**Comment by oganm** [comment]
For future reference for myself, which one did you try?

**Comment by TiamHeydari** [comment]
I actually deleted my previous version from `/Library/Java/JavaVirtualMachines/` and installed this:`jdk-10_osx-x64_bin.dmg` on my machine manually. the path of the `ermineR:::findJava()` changed to new version.
